"use client";

interface PictureProps {
  src: string;
  alt: string;
  className?: string;
  widths?: number[];
  sizes?: string;
  priority?: boolean;
}

/**
 * Picture component - provides responsive images with WebP/AVIF support
 * Automatically generates WebP and AVIF sources alongside original format
 * 
 * Usage:
 * <Picture src="/process/p1.png" alt="description" className="w-full h-full object-cover" />
 */
export default function Picture({
  src,
  alt,
  className = "",
  widths = [320, 640, 960, 1280, 1920],
  sizes = "(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw",
  priority = false,
}: PictureProps) {
  // Extract filename without extension and extension
  const lastDot = src.lastIndexOf(".");
  const base = lastDot !== -1 ? src.substring(0, lastDot) : src;
  const ext = lastDot !== -1 ? src.substring(lastDot) : "";

  const isSvg = ext === ".svg";

  // For SVGs, use standard img tag
  if (isSvg) {
    return <img src={src} alt={alt} className={className} loading={priority ? "eager" : "lazy"} />;
  }

  return (
    <picture>
      {/* AVIF sources (generated by next/image or external tool) */}
      {widths.map((w) => (
        <source
          key={`avif-${w}`}
          srcSet={`${base}-${w}w.avif ${w}w`}
          type="image/avif"
          sizes={sizes}
        />
      ))}
      {/* WebP sources */}
      {widths.map((w) => (
        <source
          key={`webp-${w}`}
          srcSet={`${base}-${w}w.webp ${w}w`}
          type="image/webp"
          sizes={sizes}
        />
      ))}
      {/* Fallback to original format */}
      <img
        src={src}
        alt={alt}
        className={className}
        loading={priority ? "eager" : "lazy"}
        decoding="async"
      />
    </picture>
  );
}